[theme]
primaryColor = "#00a8ff"
backgroundColor = "#0b0f12"
secondaryBackgroundColor = "#0f1416"
textColor = "#e8eef1"
font = "sans serif"

[server]
maxUploadSize = 5  
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false