[GOOGLE_SHEETS]
type = "service_account"
project_id = "flood-warning-system-481323"
private_key_id = "8e832e5d0dfbabaa593dda451bf86a8c6ef8d8fd"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQTt7HmP+sbVrf
tv567R7kr5fBgAYdGAO7E1ac/Sc7kv4eDP6v0+HEebBnRW9yPYabwO5WcHhPsRTI
EvLWfqu/NoOobz/0jDLyWNt7m0X8kswE1KMRmfxnW68qdUgLZfH4pk2PUwoMLfFS
aM4V/oXvfyLw8pUfnfDoewEx+jQyyMsyMvWdYsWjq5pprjrgH3TE0SPseeb/bkgS
ozg9S0BNbn94yYEnqL3p13xQv179LMobNtG53du8YVt4ainc9t+syrNJOWyye9cg
kSssRxzAKvKN1fztOjgEDtev2LxVtfHRyxj/n5fh388cnfK9fJDadzZ8I/VXBYL3
P/ZxSkhPAgMBAAECggEAH4yyhTyRDMaLSvLmXCvpz+0gaPhA9MscVYs6RRC6jnVW
86o4MN1Ahod/xkRn+r+C0bhI4OKr9jX11c+44+/Ph2h0TGB9KUbKuJXouDHuSbDa
IakrAZF2/xiN0TpuLPvFyEk32gtTrECRGlAxVnd0Ra/V1PSIzX8Ya72lkrI4kbA9
qgJFqACpzLMygCSYf6aMBvPHs2kDRH17S2rKbJPBsV04hrpAWNXjpH70BqTvPAvE
R2swBlAGFYfV5773BIlOBvEBqrztZKm8LRMVmgM0k+R4OBEzgXNxF339ginFPMsk
MrFxHPjy2QGcJUrdufbqHFgYzLN9Ty94A2aHsZeOkQKBgQD3CrRm37tx+2/7EUem
wQ4WX17QsUExuHMQdraxLnFEH22slC6fZT4MOasO8xCCJiBK1qonGgRl5y9IBxew
7ychK1CoGu1qiS7MZHDrvh+QQXYxO1mY8qwdxndxbOTYJ1FViQVd+F77va1Bpn25
YsGBRhBLVXKTepjRmClIxin6fQKBgQDX3JlwtpQku/aGCSSWzBj1pZFPEvgpc7wj
at4WureSt8Efi3Om7aLar4oI1/VgwsBaqm/l9M2jSatOuIi3dXaLfDBRVquIzNZh
4xbXq9NM+DSfku0ovwFfpT4jJlfseKkwRsUd2SMBtPm7PiI1nn4W3zCtO4ZCe2Eb
jkWW6vO7uwKBgQDMnbcyhhlxnTrxDyzzt299pFyaKla/YfEcL9e+BaOXMxjaGppL
N8Yexh0i8rw3sHCKzCZ+4JPH+6Yz2HwM9ujIFmJl+nevCBUVAhRtjjoCd9X3jRr3
Dfj1aI9CCVm6l0ZMvIMPhErX5BD/EXGM/XkdI/UXEJ0n/iFZaNi5CDl42QKBgQDD
YZnEyo1mfndRtL7Yex3wYg8XKo1SP74/tIAWxKRZ+ValLbzdj+RC2nYvMQGZtk0T
A4fK9XyX2pti4mZk374P3LWDOdaDORymdzx6s7zKwzImaX+dzNz6bH/EovUcRc6l
srjCHoKwDdWopEGklLN+EkBl3CXW0QQBRBI62qkH9wKBgB5ToaJAiirpzqfnY8F0
z6yVr7MnXtEqhdGkeNEh0c4Idf18QkLVtKqTjV5hLjb89msDeNgsts4Difwc2mqz
2zCfm649g1qSxRDcCzgo3/u+1Q2V2CGuyCFFFiRKW5lGbMCE5xrdj9JIj0t0fWRt
cuko7+2WvdPbR0DGHDqS8dUD
-----END PRIVATE KEY-----
"""
client_email = "flood-sheets-access@flood-warning-system-481323.iam.gserviceaccount.com"
client_id = "110784498522048110065"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/flood-sheets-access%40flood-warning-system-481323.iam.gserviceaccount.com"
SPREADSHEET_ID = "1wdys3GzfDfl0ohCQjUHRyJVbKQcM0VSIMgCryHB0-mc"

[SYSTEM]
admin_email = "tyarawahyusaputra@gmail.com"
admin_phone = "085156959561"
max_reports_per_day = 10
upload_folder = "uploads"